### PR TITLE
Upgrade ndarray and other deps

### PR DESCRIPTION
**Pull request by bluss**
Based on #379. Opened new PR to run tests again, need to see their status and logs.

### CODE REVIEW

**Comment by Dirreke** [comment]
I think we need merge #372 first, and then bump MSRV.

**Comment by cguentherTUChemnitz** [comment]
When i understand correctly, there is just the MSRV bump missing, what @Dirreke already pointed to. At least the one red job of CI is complaining about exactly that:

```
error: package `idna_adapter v1.2.0` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.63.0
```

**Comment by cguentherTUChemnitz** [comment]
I tried to add just the missing commit here, to update the rust versions of the CI runners. I did not find a way to add it to the existing pull-request, so i created a new one: https://github.com/rust-ndarray/ndarray-linalg/pull/389

**Comment by Dirreke** [comment]
Before we discuss MSRV, let’s rebase this PR, rerun the CI, and merge it first. Afterward, we can decide MSRV and add an MSRV test to the CI.

**Comment by cguentherTUChemnitz** [comment]
This request can be closed, since https://github.com/rust-ndarray/ndarray-linalg/pull/389 is already merged and contains the same commits.

**Pull request closed without merging**
